language: node_js
node_js:
- "12"
sudo: false
branches:
  only:
  - master
  - /20.*/
script:
- npm run test:ci
- travis_wait 30 npm run build
- npm run build:lang
- npm run build:unbundled
- |
  if [ "$TRAVIS_TEST_RESULT" == "0" ]; then
    npm run publish:autotag;
  fi
- |
  if [ "$TRAVIS_TEST_RESULT" == "0" ] && [ "$TRAVIS_SECURE_ENV_VARS" == "true" ] && [ "x$TRAVIS_TAG" != "x" ]; then
    npm run publish:cdn;
  fi
env:
  global:
  # GITHUB_TOKEN
  - secure: MLxmozticV2Zdmm96znAr4ZSXWF2ztB3DU7+9hH99LsSRj8Wly190sb7gbNY3Y5aw/3NKVO1TBdt7VvPxC2zFzzqYXbR3zpEPHkPt7YAuB8Q5jFLLYfF2i2Cxrozu5FYM5qA0dpxQZ7u3miBOp8tATFOtJQuXjaTh56FGewrcfXCantdJoPCgSmuwdi1cvfBTmRD/pDb1X5P7sC7KmROdfAZEHwAVgwMf5h5xpVvKnh245qPtkM/vg4hkTqI/72nmaV7LMrG0Uio39XOMFwjOFzvOqBcbuyNXjgNVuF0pbRvSdEUMKEtvwZ8IhwV/yCKAVymSLFbZtDmbqJk7tEn9Atp/iTATTpzxFU547DcPW7YL+vakL3sCKhukxz4VzwGDosyZIc1zgrBaS6u+q4U14JkuN55UaPlnbc+AHxYr3of+ahuaGD93wMam9uzsMuFMvfXExVitZ4s9lvCK8bwz6jJ0CK5+p1zkA1U0A3vH1skAZvwv/gdUppXO7OLc4fXSV8VSDvkiBRh7vtNc0rUsS3V053M4PRokuhsviQhacda2BsticTAC/yRuTjFBj+Puun8QYuq+tghALXyIUAzWXlP/BV8s6JrrmooeyRz2REuu795kdu+NIT8E80hJHzYbbiNdGk9mZ1ER7wEaL6uUAUyAiBAoTAhFuvmKkDSBEA=
  # RALLY_API_KEY
  - secure: DHFdl8Lb94EZtKvq4uvpu9BLB4KOw00pkH40TQmFhJGDNo6uJ1mK/fD5UtBe/MY1RW9v1TK6Bh3F/VArp3RwdtNwcmcG/wTHKYJFhGMgEwlv08eeHJ3GePKJsbeUFjBj9rBPK6XylUfXa6AWCNV5wc4u3edDoKxEJ7OxDMyYv94hFxADsIjbLHVn2Z8cqE6gSbAY+kwEVxXWDSUUEkzAsEOxrdngAOMx9YSEp+SyY2tEzUbq7qXHa7r10aVMaFpX9glpKgiftSfRW5ySiJeUU6JYLoFLE0J52E+A/LRGIjL+i4p/yDblPhM6Gpd84GCBBNyMDX3u/RueAGZ2H6W8y0oJJcvCHOi6cdbu0hFYsWALT1kj5Gchp33NtuEsh78WcziaU+L4Fo+9ELuepiAAhu98eoTFiOHVqhSbnPFkzAUTx1uF4OOGG7ZGLrp0dzB9v3SYM0XTJQ0RmlO4XbWrXhbC5haX4PzV/HKzT6Af1C7SLCjeI4FsSxmW119Km4DvxFskOzKg40CZI3IyQk3aiH/okWYegrLl48Wu1nvgP/uGbBGA51P0x2D8OseO8TkIqlR+DYbgETIUbnpawgYrZq1J9UFlZiJIFKGET9WZiJvqXoojhq02zrnHwAzAeG0ogXGU0/JTsbnISA+WMMY3h0C/92Ntl/jDsoy3BL1TP+U=
